--Volcado
BULK INSERT PRODUCTO
	FROM 'C:\PRODUCTOS.TXT'
	WITH(
		FIELDTERMINATOR=',',
		ROWTERMINATOR='\n',
		FIRSTROW=1
	)
GO

--También podríamos usar la siguiente sentencia
BULK INSERT PRODUCTO
	FROM 'C:\PRODUCTOS.TXT'
	WITH(
		FIELDTERMINATOR=',',
		ROWTERMINATOR='\n'
      )
GO


--Declaracion de variables
DECLARE @COD CHAR(4),@DES VARCHAR(40),@PRE MONEY,@SAC INT,@SMI INT,@UNI VARCHAR(30),@LIN INT,@IMP CHAR(1)
SET @COD='P001'
SET @DES='PAPEL BOND A-4 ATLAS'
SET @PRE=18.50 
SET @SAC=200
SET @SMI=1500
SET @UNI='MLL'
SET @LIN='2'
SET @IMP='V'

--Aplicando la sentencia MERGE
MERGE PRODUCTO AS TARGET
	USING (SELECT @COD,@DES,@PRE,@SAC,@SMI,@UNI,@LIN,@IMP)
	AS SOURCE (COD_PRO,DES_PRO,PRE_PRO,SAC_PRO,SMI_PRO,UNI_PRO,LIN_PRO,IMP_PRO)
	ON (TARGET.COD_PRO = SOURCE.COD_PRO)
	WHEN MATCHED THEN
	UPDATE SET DES_PRO=SOURCE.DES_PRO,PRE_PRO=SOURCE.PRE_PRO,
			   SAC_PRO=SOURCE.SAC_PRO,SMI_PRO=SOURCE.SMI_PRO,
			   UNI_PRO=SOURCE.UNI_PRO,LIN_PRO=SOURCE.LIN_PRO,
			   IMP_PRO=SOURCE.IMP_PRO
	WHEN NOT MATCHED THEN
	INSERT VALUES(SOURCE.COD_PRO, SOURCE.DES_PRO,SOURCE.PRE_PRO,
	              SOURCE.SAC_PRO,SOURCE.SMI_PRO,SOURCE.UNI_PRO,
				  SOURCE.LIN_PRO,SOURCE.IMP_PRO);
GO
